### ISSUE TITLE
Extra Spaces In The Regmods?

### ISSUE THREAD

**Issue by bigblueswope** [boingomw/Lazerbearsharkpig#1]
https://github.com/boingomw/Lazerbearsharkpig/blob/master/raw_parts/dwatchlists.csv

Line 3, are there extra spaces in the regmod definitions?

windows\ nt\currentversion x2
browser\ helper\ objects\

**Comment by boingomw** [comment]
I'm not sure its the spaces, but something is wrong with that watchlist entry.  lemme investigate.

**Comment by bigblueswope** [comment]
I'll test on it too.

**Comment by bigblueswope** [comment]
I did some digging and it isn't a typo.  The path contains "Windows NT" so the "\windows\ nt" is backslash escaping the space.  Now to see if the rule actually works!  :-)

**Comment by bigblueswope** [comment]
Just tested on Windows Server 2012 and it works for 
regmod:software\microsoft\windows\currentversion\run*
Just tested on Window 7 and it works for 
regmod:registry\machine\software\microsoft\windows\ nt\currentversion\winlogon\userinit

**Comment by boingomw** [comment]
I LOVE that the 1/2 the spaces have to be escaped, and 1/2 don't, but that's how it is.  However, the problem was a ) missing at the end of the entire search.  All fixed now!
